### ISSUE TITLE
Different results for CPUfeatures.exe

### ISSUE THREAD

**Issue by dgarlor** [albertony/cpufeatures#1]
Hello,
Nice project, I created my own functions based on microsoft example but your project is more complete. 
Sadly, I find an inconsistency in a virtual machine I'm using for testing.

For avx2 I have different results depending on using the default method or the microsoft/avx methods... you have any clue? 

Default says: AVX2 not supported 
-m and -a: AVX2 supported

Same response in a virtual machine with Windows XP... are this functions depending on the OS or only in the hardware?

**Comment by albertony** [comment]
Thank you, appreciate the feedback.

Looking at the code I would guess you get different result for AVX as well?

Reason is that the actual AVX2 check seems more or less identical between the variants, but in the default method it is only considered when AVX is detected first - and that has some additional logic: The AVX detection in the default method seems to follow the algorithm as described here: https://stackoverflow.com/questions/44144763/avx-feature-detection-using-sigill-versus-cpu-probing/44157138#44157138. This means it not only checks the cpu flag specifically indicating AVX hardware support, which is what the microsoft method (`-m` and `-m -a`) does, it also checks that the OS supports it and has it enabled!

If the above explains your observations, I have not decided yet what to do about it. One option is to keep it as is, and just document it properly. The -m method will then tell you if it is "supported" by hardware, while the default method will tell you if it is "enabled" (and then implicitely also supported) by hardware and os.

Edit: And so I did - updated readme. Let me know what you think.

**Comment by dgarlor** [comment]
Thank you very much for your answer. You are totally right, I wasn't able to understand de default method code but it has to take into account the OS support (which is exactly what I need!).

Readme is clearer now... Thanks!
